"""Seed signal definitions used by the baseline analyzer."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final


@dataclass(frozen=True)
class SignalDefinition:
    """Configuration for a baseline stylistic signal."""

    code: str
    name: str
    category: str
    description: str
    patterns: tuple[str, ...]
    severity_default: float
    confidence: float
    rewrite_strategies: tuple[str, ...]
    rationale: str


SIGNALS: Final[tuple[SignalDefinition, ...]] = (
    SignalDefinition(
        code="GENERIC_SIGNIFICANCE",
        name="generic_significance",
        category="inflation",
        description="Inflates importance without adding concrete information.",
        patterns=(r"\bpivotal moment\b", r"\bcrucial role\b", r"\bmarks? a shift\b"),
        severity_default=0.74,
        confidence=0.84,
        rewrite_strategies=("replace_with_concrete_fact", "delete_if_empty"),
        rationale="The phrase signals importance but does not say what concretely changed.",
    ),
    SignalDefinition(
        code="BROADER_TRENDS_PADDING",
        name="broader_trends_padding",
        category="genericity",
        description="Claims broader significance without evidence.",
        patterns=(r"\breflects broader trends\b", r"\bwider landscape\b", r"\bbroader landscape\b"),
        severity_default=0.7,
        confidence=0.82,
        rewrite_strategies=("replace_with_specific_claim", "delete_if_empty"),
        rationale="The wording gestures at context instead of naming the supporting evidence.",
    ),
    SignalDefinition(
        code="LEGACY_LANGUAGE",
        name="legacy_language",
        category="inflation",
        description="Uses legacy/impact wording without concrete support.",
        patterns=(r"\benduring impact\b", r"\blasting significance\b", r"\blegacy\b"),
        severity_default=0.67,
        confidence=0.79,
        rewrite_strategies=("replace_with_specific_claim", "delete_if_empty"),
        rationale="The passage names legacy or impact without saying what the legacy is.",
    ),
    SignalDefinition(
        code="NOTABILITY_PADDING",
        name="notability_padding",
        category="inflation",
        description="Overstates attention or public recognition in generic terms.",
        patterns=(r"\bwidely recognized\b", r"\bgained significant attention\b", r"\bnotable presence\b"),
        severity_default=0.66,
        confidence=0.77,
        rewrite_strategies=("name_source_or_remove",),
        rationale="The wording implies significance without attribution or concrete scope.",
    ),
    SignalDefinition(
        code="MEDIA_COVERAGE_FILLER",
        name="media_coverage_filler",
        category="genericity",
        description="References media coverage without specifics.",
        patterns=(r"\bcovered by major outlets\b", r"\bprofiled in regional media\b"),
        severity_default=0.71,
        confidence=0.8,
        rewrite_strategies=("name_source_or_remove",),
        rationale="The passage mentions coverage but withholds who covered it.",
    ),
    SignalDefinition(
        code="SUPERFICIAL_ANALYSIS_TAG",
        name="superficial_analysis_tag",
        category="style",
        description="Adds a shallow interpretive tail such as highlighting or underscoring.",
        patterns=(r"\bhighlighting\b", r"\bunderscoring\b", r"\breflecting\b"),
        severity_default=0.63,
        confidence=0.74,
        rewrite_strategies=("tighten_interpretive_tail",),
        rationale="The sentence ends in a generic interpretive tag instead of a specific claim.",
    ),
    SignalDefinition(
        code="ABSTRACT_IMPACT_CHAIN",
        name="abstract_impact_chain",
        category="style",
        description="Stacks abstract impact language.",
        patterns=(r"\bfostering innovation\b", r"\benhancing engagement\b", r"\bcontributing to growth\b"),
        severity_default=0.72,
        confidence=0.82,
        rewrite_strategies=("swap_abstract_nouns_for_verbs",),
        rationale="The phrase relies on abstract outcome language rather than concrete action.",
    ),
    SignalDefinition(
        code="PROMOTIONAL_PUFFERY",
        name="promotional_puffery",
        category="style",
        description="Uses ad-like promotional language.",
        patterns=(r"\bvibrant\b", r"\brenowned\b", r"\bgroundbreaking\b", r"\bnestled in the heart of\b"),
        severity_default=0.73,
        confidence=0.85,
        rewrite_strategies=("neutralize_promotional_language",),
        rationale="The wording reads as promotion rather than accountable description.",
    ),
    SignalDefinition(
        code="PEACOCK_ADJECTIVES",
        name="peacock_adjectives",
        category="style",
        description="Ungrounded positive adjectives.",
        patterns=(r"\bremarkable\b", r"\boutstanding\b", r"\bexceptional\b"),
        severity_default=0.65,
        confidence=0.76,
        rewrite_strategies=("neutralize_promotional_language",),
        rationale="The adjective praises the subject without supporting evidence.",
    ),
    SignalDefinition(
        code="VAGUE_ATTRIBUTION",
        name="vague_attribution",
        category="genericity",
        description="Attributes claims to unnamed authorities.",
        patterns=(r"\bexperts argue\b", r"\bobservers say\b", r"\bindustry reports suggest\b"),
        severity_default=0.78,
        confidence=0.88,
        rewrite_strategies=("name_source_or_remove",),
        rationale="The claim points to authority without naming a source the reader can inspect.",
    ),
    SignalDefinition(
        code="WEASEL_GENERALIZATION",
        name="weasel_generalization",
        category="genericity",
        description="Uses weak quantified claims without support.",
        patterns=(r"\bsome critics\b", r"\bseveral publications\b", r"\bmany believe\b"),
        severity_default=0.69,
        confidence=0.81,
        rewrite_strategies=("name_source_or_remove",),
        rationale="The sentence gestures at consensus without enough evidence.",
    ),
    SignalDefinition(
        code="OUTLINE_CHALLENGES_SECTION",
        name="outline_challenges_section",
        category="structure",
        description="Adds canned challenges language.",
        patterns=(r"\bdespite its strengths, it faces challenges\b", r"\bfaces several challenges\b"),
        severity_default=0.76,
        confidence=0.86,
        rewrite_strategies=("replace_with_specific_claim", "delete_if_empty"),
        rationale="The section sounds like a template heading rather than a concrete observation.",
    ),
    SignalDefinition(
        code="FUTURE_PROSPECTS_SECTION",
        name="future_prospects_section",
        category="structure",
        description="Uses canned future outlook language.",
        patterns=(r"\bfuture prospects\b", r"\bfuture outlook\b", r"\blooking ahead\b"),
        severity_default=0.74,
        confidence=0.85,
        rewrite_strategies=("replace_with_specific_claim", "delete_if_empty"),
        rationale="The closing relies on a stock future-oriented frame instead of advancing the argument.",
    ),
    SignalDefinition(
        code="CANNED_TRANSITION_ADDITIONALLY",
        name="canned_transition_additionally",
        category="structure",
        description="Uses repetitive additionally-style transitions.",
        patterns=(r"(?m)^\s*Additionally,", r"(?m)^\s*Furthermore,"),
        severity_default=0.61,
        confidence=0.72,
        rewrite_strategies=("replace_canned_transition",),
        rationale="The sentence opens with a stock transition that often adds rhythm without substance.",
    ),
    SignalDefinition(
        code="CANNED_TRANSITION_OVERALL",
        name="canned_transition_overall",
        category="structure",
        description="Uses generic wrap-up transitions.",
        patterns=(r"(?m)^\s*Overall,", r"(?m)^\s*In summary,", r"(?m)^\s*In conclusion,"),
        severity_default=0.7,
        confidence=0.82,
        rewrite_strategies=("delete_redundant_summary",),
        rationale="The sentence announces a summary instead of providing one with specific content.",
    ),
    SignalDefinition(
        code="BUZZWORD_VERB_CLUSTER",
        name="buzzword_verb_cluster",
        category="style",
        description="Overuses polished but empty verbs.",
        patterns=(r"\bunderscores\b", r"\bshowcases\b", r"\bdelves into\b", r"\bgarnered\b"),
        severity_default=0.68,
        confidence=0.8,
        rewrite_strategies=("simplify_to_plain_statement",),
        rationale="The verb adds polish but often obscures the underlying claim.",
    ),
    SignalDefinition(
        code="ABSTRACT_NOUN_OVERUSE",
        name="abstract_noun_overuse",
        category="style",
        description="Leans on abstract nouns such as landscape or framework.",
        patterns=(r"\blandscape\b", r"\btapestry\b", r"\binterplay\b", r"\bframework\b"),
        severity_default=0.66,
        confidence=0.77,
        rewrite_strategies=("swap_abstract_nouns_for_verbs",),
        rationale="The sentence uses abstraction where a concrete noun or verb would say more.",
    ),
    SignalDefinition(
        code="COPULA_AVOIDANCE",
        name="copula_avoidance",
        category="style",
        description="Avoids simple is/are/has constructions.",
        patterns=(r"\bserves as\b", r"\bstands as\b", r"\bfeatures\b", r"\boffers\b"),
        severity_default=0.64,
        confidence=0.76,
        rewrite_strategies=("simplify_to_plain_statement",),
        rationale="The phrasing often hides a simpler underlying statement.",
    ),
    SignalDefinition(
        code="MECHANICAL_BOLDFACE",
        name="mechanical_boldface",
        category="formatting",
        description="Uses bold emphasis in a mechanical key-takeaway style.",
        patterns=(r"\*\*key takeaways\*\*", r"\*\*important\*\*"),
        severity_default=0.58,
        confidence=0.7,
        rewrite_strategies=("remove_formatting_emphasis",),
        rationale="The emphasis format resembles generated summary formatting rather than authored prose.",
    ),
    SignalDefinition(
        code="STRUCTURED_LISTICLE_TONE",
        name="structured_listicle_tone",
        category="structure",
        description="Uses neat listicle-style structure.",
        patterns=(r"(?m)^\s*\d+\.\s", r"(?m)^\s*[-*]\s"),
        severity_default=0.5,
        confidence=0.63,
        rewrite_strategies=("review_structure_for_authenticity",),
        rationale="The structure may be template-driven if it dominates otherwise plain prose.",
    ),
    SignalDefinition(
        code="COLLABORATIVE_CHAT_RESIDUE",
        name="collaborative_chat_residue",
        category="chat_residue",
        description="Leaves chatbot-style conversational residue.",
        patterns=(r"\bi hope this helps\b", r"\bwould you like\b", r"\bhere is a breakdown\b"),
        severity_default=0.87,
        confidence=0.93,
        rewrite_strategies=("remove_chat_residue",),
        rationale="The wording reads like a conversational assistant rather than document prose.",
    ),
    SignalDefinition(
        code="KNOWLEDGE_CUTOFF_DISCLAIMER",
        name="knowledge_cutoff_disclaimer",
        category="chat_residue",
        description="Includes last-training-update style disclaimers.",
        patterns=(r"\bas of my last training update\b", r"\bbased on available information\b"),
        severity_default=0.9,
        confidence=0.95,
        rewrite_strategies=("remove_chat_residue",),
        rationale="The line explicitly exposes model-era disclaimer language.",
    ),
    SignalDefinition(
        code="SOURCE_SCARCITY_SPECULATION",
        name="source_scarcity_speculation",
        category="citations",
        description="Speculates about missing sources.",
        patterns=(r"\blimited publicly available information\b", r"\bappears to be little information\b"),
        severity_default=0.71,
        confidence=0.8,
        rewrite_strategies=("state_known_limits_plainly",),
        rationale="The sentence speculates about source scarcity instead of simply naming the limit.",
    ),
    SignalDefinition(
        code="BROKEN_EXTERNAL_LINK_PATTERN",
        name="broken_external_link_pattern",
        category="citations",
        description="Contains implausible or malformed external links.",
        patterns=(r"https?://[^\s)]+\.invalid", r"https?://example\.com/[^\s)]*source"),
        severity_default=0.83,
        confidence=0.9,
        rewrite_strategies=("verify_or_remove_reference",),
        rationale="The link pattern suggests placeholder or fabricated supporting material.",
    ),
    SignalDefinition(
        code="UNRELATED_DOI_PATTERN",
        name="unrelated_doi_pattern",
        category="citations",
        description="Uses DOI-shaped references that require verification.",
        patterns=(r"\b10\.\d{4,9}/[-._;()/:A-Za-z0-9]+\b",),
        severity_default=0.6,
        confidence=0.62,
        rewrite_strategies=("verify_or_remove_reference",),
        rationale="The DOI may be valid, but it needs source verification before it adds trust.",
    ),
    SignalDefinition(
        code="BOOK_CITATION_WEAK_SUPPORT",
        name="book_citation_weak_support",
        category="citations",
        description="Uses weak generic book citations.",
        patterns=(r"\bin [A-Z][A-Za-z ]+ \(\d{4}\)\b", r"\bsee also [A-Z][A-Za-z ]+, \d{4}\b"),
        severity_default=0.57,
        confidence=0.61,
        rewrite_strategies=("verify_or_remove_reference",),
        rationale="The citation looks generic and may not support the nearby claim clearly.",
    ),
    SignalDefinition(
        code="SEARCH_LINK_LEAKAGE",
        name="search_link_leakage",
        category="citations",
        description="Leaks search-result links or malformed references.",
        patterns=(r"https?://www\.google\.com/search\?", r"\bsearch\?q="),
        severity_default=0.89,
        confidence=0.94,
        rewrite_strategies=("verify_or_remove_reference",),
        rationale="Search-result URLs should not appear as final citations or polished prose.",
    ),
    SignalDefinition(
        code="DIDACTIC_DISCLAIMER",
        name="didactic_disclaimer",
        category="style",
        description="Uses teacherly prefatory language.",
        patterns=(r"\bit is important to note\b", r"\bworth noting\b"),
        severity_default=0.68,
        confidence=0.81,
        rewrite_strategies=("remove_teacherly_preface",),
        rationale="The phrase tells the reader how to read the point instead of stating it directly.",
    ),
    SignalDefinition(
        code="SECTION_SUMMARY_RESTATEMENT",
        name="section_summary_restatement",
        category="structure",
        description="Restates the obvious at the end of a section.",
        patterns=(r"\bin summary\b", r"\boverall, this shows\b", r"\bto summarize\b"),
        severity_default=0.72,
        confidence=0.84,
        rewrite_strategies=("delete_redundant_summary",),
        rationale="The line often repeats what the section already established.",
    ),
    SignalDefinition(
        code="PROMPT_REFUSAL_RESIDUE",
        name="prompt_refusal_residue",
        category="chat_residue",
        description="Contains AI refusal traces.",
        patterns=(r"\bas an ai language model\b", r"\bi cannot assist with that\b", r"\bi'm sorry, but\b"),
        severity_default=0.95,
        confidence=0.98,
        rewrite_strategies=("remove_chat_residue",),
        rationale="The passage contains explicit assistant refusal language.",
    ),
)

SIGNALS_BY_CODE: Final[dict[str, SignalDefinition]] = {signal.code: signal for signal in SIGNALS}
